# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  install:
    cmds:
      - task: install-darwin
      - task: install-windows      
      
  install-darwin:
    platforms: [darwin]
    cmds:      
      - task: build
      - cmd: mkdir -p ~/Applications
      - cmd: rm -rf ~/Applications/Granite.app
      - cmd: mv app/build/bin/Granite.app ~/Applications/

  install-windows:
    platforms: [windows]
    cmds:
      - task: build
      - cmd: mkdir -p %LOCALAPPDATA%\Programs
      - cmd: rm -f %LOCALAPPDATA%\Programs\Granite.exe
      - cmd: mv app/build/bin/Granite.exe %LOCALAPPDATA%\Programs\

  build:
    dir: app
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - wails build
  
