# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build:
    cmds:
      - npm run build
      - go build -o bin/granite ./cmd/granite

  run:
    cmds:
      - npm run build
      - go run ./cmd/granite

  install:
    cmds:
      - npm run build
      - go install ./cmd/granite
