import type { DatabaseAdapter, Driver } from "./types";

const tableColumns: Record<Driver, { id: string; name: string }> = {
  postgres: {
    id: "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    name: "TEXT NOT NULL",
  },
  mysql: {
    id: "BIGINT AUTO_INCREMENT PRIMARY KEY",
    name: "VARCHAR(255) NOT NULL",
  },
  sqlite: { id: "INTEGER PRIMARY KEY", name: "TEXT NOT NULL" },
  sqlserver: {
    id: "BIGINT IDENTITY(1,1) PRIMARY KEY",
    name: "NVARCHAR(255) NOT NULL",
  },
  oracle: {
    id: "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    name: "VARCHAR2(255) NOT NULL",
  },
  // Identity columns and primary keys are not portable across Trino connectors.
  trino: { id: "BIGINT", name: "VARCHAR" },
};

export function createTableTemplate(
  adapter: DatabaseAdapter,
  existingTables: string[] = [],
): string {
  const names = new Set(existingTables.map((name) => name.toLowerCase()));
  let name = "new_table";
  for (let suffix = 2; names.has(name); suffix++) name = `new_table_${suffix}`;
  const columns = tableColumns[adapter.driver];
  return `CREATE TABLE ${adapter.quoteIdentifier(name)} (
  ${adapter.quoteIdentifier("id")} ${columns.id},
  ${adapter.quoteIdentifier("name")} ${columns.name}
);`;
}
